version: "3"

services:
#  db:
#    image: mariadb
#    environment:
#      - MYSQL_ROOT_PASSWORD=supersecret
#      - MYSQL_DATABASE=unimus
#      - MYSQL_USER=unimus
#      - MYSQL_PASSWORD=secret
#      #- TZ=Europe/Budapest
#    volumes:
#      - './db:/var/lib/mysql'
#      - '/etc/localtime:/etc/localtime:ro'
#    restart: unless-stopped
  unimus-core:
    image: croc/unimus-core
    environment:
      # unimus server address
      - UNIMUS_SERVER_ADDRESS=172.17.0.1
      - UNIMUS_SERVER_PORT=8085
      - UNIMUS_SERVER_ACCESS_KEY=secretsecret
      # base memory params for java
      - XMX=1024M
      - XMS=256M
      # OR more customizable JAVA options
#      - JAVA_OPTS=-Xms128M -Xmx512M
      - TZ=Europe/Budapest
    volumes:
      - './config:/etc/unimus-core'
      #- '/etc/localtime:/etc/localtime:ro'
#    depends_on:
#      - db
#    ports:
#      - '8085:8085'
    restart: unless-stopped
