version: "3"

services:
  unimus-core:
    image: croc/unimus-core:dev
    environment:
      # unimus server address
      - UNIMUS_SERVER_ADDRESS=192.168.72.133
      - UNIMUS_SERVER_PORT=8085
      - UNIMUS_SERVER_ACCESS_KEY=i...........................................................................p
      # base memory params for java
      - XMX=1024M
      - XMS=256M
      # OR more customizable JAVA options
#      - JAVA_OPTS=-Xms128M -Xmx512M
      - TZ=Europe/Budapest
    volumes:
      - './config:/etc/unimus-core'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
